languageCode = "en-us"
title = "Catugo"
baseURL = "http://catu.ga/cupper/"
canonifyURLs = true
theme = "cupper"
publishDir = "docs"

[params]
  description = "Lorem Ipsum is simply ***dummy*** text of the ***printing*** and ***typesetting*** industry."
  codePenUser = "Heydon"
