languageCode = "en-us"
title = "Catugo"
baseURL = "https://catagranic.github.io/cupper/"
canonifyURLs = true
theme = "cupper"
publishDir = "docs"

[params]
  description = "Lorem Ipsum is simply ***dummy*** text of the ***printing*** and ***typesetting*** industry."
  codePenUser = "Heydon"
